crystal_diffusion/main_utils.py
crystal_diffusion/models/position_diffusion_lightning_model.py
crystal_diffusion/train_diffusion.py
crystal_diffusion/utils/logging_utils.py
requirements.txt

A mini-PR to fix config file copy and logging of all the HPs.

Better logging

---

examples/narval/diffusion/config_diffusion.yaml
examples/narval/diffusion/run_diffusion.sh
requirements.txt

Some minor changes to run smoothly on Narval.

Fix narval

---

crystal_diffusion/analysis/timing_adjacency_matrix_calculations.py
crystal_diffusion/models/mace_utils.py
crystal_diffusion/utils/neighbors.py
requirements.txt
tests/data/diffusion/test_data_loader.py
tests/fake_data_utils.py
tests/models/test_mace_utils.py
tests/models/test_position_diffusion_lightning_model.py
tests/samplers/test_noisy_position_sampler.py
tests/samplers/test_predictor_corrector_position_sampler.py
tests/samplers/test_variance_sampler.py
tests/score/test_wrapped_gaussian_score.py
tests/test_fake_data_utils.py
tests/utils/test_neighbors.py
tests/utils/test_tensor_utils.py

This PR presents code that computes the adjacency matrix and accompanying data without leaving the GPU.
This code is then introduced into the MACE utils module. More robust tests on this integration should be done next.

Adjacency matrix on gpu

---

crystal_diffusion/models/mace_utils.py
crystal_diffusion/models/model_loader.py
crystal_diffusion/models/position_diffusion_lightning_model.py
crystal_diffusion/models/score_network.py
examples/local/diffusion/config_diffusion_mace.yaml
tests/models/test_score_network.py

2nd attempt at a MACE network, now using a graph data structure that should not be swapping device

Mace as score network v2

---

crystal_diffusion/models/score_network.py
crystal_diffusion/utils/neighbors.py

very small fixes required to run on gpu

Debug mace on gpu

---

crystal_diffusion/models/score_network.py

Introduce the radial cutoff when we create MACE's input!

Use the radial cutoff!

---

tests/models/test_score_network.py

Fixing the tests that were broken and decorated `not_on_github`.

Fix tests.

---

crystal_diffusion/models/mace_utils.py
crystal_diffusion/models/model_loader.py
crystal_diffusion/models/position_diffusion_lightning_model.py
crystal_diffusion/models/score_network.py
crystal_diffusion/models/score_prediction_head.py
examples/local/diffusion/config_diffusion_mace_equivariant_head.yaml
examples/local/diffusion/config_diffusion_mace_mlp_head.yaml
examples/local/diffusion/config_diffusion_mlp.yaml
examples/local/diffusion/run_diffusion.sh
tests/fake_data_utils.py
tests/models/test_mace_utils.py
tests/models/test_score_network.py
tests/models/test_score_prediction_head.py
tests/test_train_diffusion.py

This code implements a first equivariant prediction head. It also uses `e3nn` to extract dimensions of representations.

Equivariant head

---

crystal_diffusion/callbacks/callback_loader.py
crystal_diffusion/callbacks/loss_monitoring_callback.py
crystal_diffusion/callbacks/sampling_callback.py
crystal_diffusion/loggers/logger_loader.py
crystal_diffusion/models/mace_utils.py
crystal_diffusion/models/model_loader.py
crystal_diffusion/models/position_diffusion_lightning_model.py
crystal_diffusion/models/score_network.py
crystal_diffusion/models/score_prediction_head.py
examples/local/diffusion/config_diffusion_mace_equivariant_head.yaml
examples/local/diffusion/config_diffusion_mace_mlp_head.yaml
examples/local/diffusion/config_diffusion_mlp.yaml
examples/local/diffusion/run_diffusion.sh
tests/fake_data_utils.py
tests/models/test_mace_utils.py
tests/models/test_score_network.py
tests/models/test_score_prediction_head.py
tests/test_train_diffusion.py

This PR is on top of #42 . 
A new callback to plot the loss contribution as a function of `sigma`. Also, some spring cleaning in the callbacks. The equivariant head is also made multi-layers.

Log loss per time

---

data/si_diffusion_1x1x1_large/create_data.sh
data/si_diffusion_1x1x1_large/in.si.lammps

generate  the lammps dataset and crop the first steps with tail. Much faster dataset generation

script to create a large 1x1x1 dataset 

---

examples/mila_cluster/diffusion/config_diffusion_mace.yaml
examples/mila_cluster/diffusion/config_diffusion_mlp.yaml
examples/mila_cluster/diffusion/config_mace_equivariant_head.yaml
examples/mila_cluster/diffusion/config_mace_mlp_head.yaml
examples/mila_cluster/diffusion/run_diffusion.sh

just a sample script to run on mila cluster

slurm script for mila cluster

---

crystal_diffusion/analysis/generator_sample_analysis_utils.py
crystal_diffusion/callbacks/loss_monitoring_callback.py
crystal_diffusion/callbacks/sampling_callback.py
crystal_diffusion/generators/ode_position_generator.py
crystal_diffusion/models/diffusion_mace.py
crystal_diffusion/models/loss.py
crystal_diffusion/models/model_loader.py
crystal_diffusion/models/position_diffusion_lightning_model.py
crystal_diffusion/models/score_networks/diffusion_mace_score_network.py
crystal_diffusion/utils/tensor_utils.py
examples/config_files/diffusion/config_diffusion_mace.yaml
examples/config_files/diffusion/config_diffusion_mace_orion.yaml
examples/config_files/diffusion/config_diffusion_mlp.yaml
examples/config_files/diffusion/config_diffusion_mlp_orion.yaml
examples/config_files/diffusion/config_mace_equivariant_head.yaml
examples/config_files/diffusion/config_mace_mlp_head.yaml
experiment_analysis/sampling_analysis/diffusion_mace_ode_sampling_analysis.py
experiment_analysis/sampling_analysis/diffusion_mace_score_and_partial_ode_analysis.py
experiment_analysis/sampling_analysis/generate_partial_ode_trajectories.py
experiment_analysis/score_analysis/compute_scores_along_path.py
experiment_analysis/score_analysis/plot_scores_along_path.py
setup.py
tests/models/test_loss.py
tests/models/test_position_diffusion_lightning_model.py
tests/test_train_diffusion.py

This PR is on top of #59 . 
Code to weight the loss with a function of `sigma` in order to force the training to emphasize larger values of `sigma`.

Weighting the loss

---

crystal_diffusion/analysis/analytic_score/exploring_langevin_generator/__init__.py
crystal_diffusion/analysis/analytic_score/exploring_langevin_generator/generate_sample_energies.py
crystal_diffusion/analysis/analytic_score/exploring_langevin_generator/plot_sample_energies.py
crystal_diffusion/analysis/analytic_score/perfect_score_loss_analysis.py
crystal_diffusion/callbacks/sampling_callback.py
crystal_diffusion/generators/position_generator.py
crystal_diffusion/models/score_networks/analytical_score_network.py
crystal_diffusion/models/score_networks/mlp_score_network.py
data/si_diffusion_1x1x1_single_example/create_data.sh
data/si_diffusion_1x1x1_single_example/in.si.lammps
data/si_diffusion_2x2x2_single_example/create_data.sh
data/si_diffusion_2x2x2_single_example/in.si.lammps
examples/config_files/diffusion/config_diffusion_mlp.yaml
tests/generators/test_langevin_generator.py
tests/models/score_network/test_score_network.py
tests/models/test_analytical_score_network.py
tests/models/test_diffusion_mace.py
tests/models/test_position_diffusion_lightning_model.py
tests/test_train_diffusion.py

This code was written to play with the ideas of overfitting a simple model. It's main contributions are  a 'better' analytical model that relies on our conditional score implementation and a 'better' MLP model that uses an embedding for sigma(t).

Overfit 222

---

crystal_diffusion/analysis/generator_sample_analysis_utils.py
crystal_diffusion/utils/ovito_utils.py
experiment_analysis/sampling_analysis/generate_partial_ode_trajectories.py
experiment_analysis/sampling_analysis/sampling_EGNN_sept_10/generate_trajectory_visualization.py
experiment_analysis/sampling_analysis/sampling_EGNN_sept_10/identify_trajectories_by_energy.py
experiment_analysis/sampling_analysis/sampling_EGNN_sept_10/plot_energies.py
requirements.txt
sanity_checks/visualizing_fake_trajectories_with_ovito/__init__.py
sanity_checks/visualizing_fake_trajectories_with_ovito/fake_data_utils.py
sanity_checks/visualizing_fake_trajectories_with_ovito/generate_fake_trajectory_visualization.py
tests/test_train_diffusion.py

This PR introduces code to generate "partial trajectories" from a reference configuration in order to probe de behavior of a SOTA model.
Some code to prepopulate an OVITO visualization pipeline is also presented. 
The analysis that this code was used to generate can be seen here: https://www.notion.so/Analysing-Si-2x2x2-trajectories-from-EGNN_Sept_10-103690083be480129aa3c5cab6ac1638

Visualizing paths

---

crystal_diffusion/models/position_diffusion_lightning_model.py

Small fix to make it possible to NOT define a metric_parameter.

Only look at metric_parameters if draw_samples is True.

---

data/SiGe_diffusion_2x2x2/config.yaml
data/SiGe_diffusion_2x2x2/create_data.sh
data/SiGe_diffusion_2x2x2/in.SiGe.lammps
data/SiGe_diffusion_3x3x3/config.yaml
data/SiGe_diffusion_3x3x3/create_data.sh
data/SiGe_diffusion_3x3x3/in.SiGe.lammps

Scripts to generate new datasets. I will add these datasets to the Data Keep shortly.

New datasets

---

src/diffusion_for_multi_scale_molecular_dynamics/generators/langevin_generator.py
src/diffusion_for_multi_scale_molecular_dynamics/generators/predictor_corrector_axl_generator.py
tests/generators/test_langevin_generator.py
tests/sampling/test_diffusion_sampling.py

I Did a rebase from commit 60ce99fbb3a4ddc51dad23e390fa3f821faf0b7a. This only introduced conflicts in `langevin_generator.py` which I fixed. There are no more conflicts and all the tests pass.

Fix conflicts

---

src/diffusion_for_multi_scale_molecular_dynamics/generators/load_sampling_parameters.py

Fix match case.

---

experiments/analysis/visualize_score_vector_field_2D.py
experiments/regularization_toy_problem/visualization_utils.py

Missing viz method.

---

experiments/score_on_a_path/compute_scores_on_a_path.py
experiments/score_on_a_path/plot_score_on_path.py
experiments/score_on_a_path/trajectory_pkl_to_ovito.py

these are the scripts for the following experiment: take a sample at low energy (preferably near equilibrium), move one atom towards its nearest neighbor, compute the score and optionally the jacobian along that trajectory for different values of sigma. The scripts include a bridge from a saved trajectory (list of AXLs) to XYZ files usable by OVITO.

Score on a path

---

src/diffusion_for_multi_scale_molecular_dynamics/models/score_networks/force_field_augmented_score_network.py
src/diffusion_for_multi_scale_molecular_dynamics/sample_diffusion.py
tests/test_sample_diffusion.py

Here I introduce some minor changes to make it easy to wrap an `axl_network` with an ad-hoc repulsive "force field" when sampling.  This will be useful to provide a baseline to other regularization approaches.

Sampling with force field

---

src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/benchmark.py
src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/utils.py
src/diffusion_for_multi_scale_molecular_dynamics/models/axl_diffusion_lightning_model.py
src/diffusion_for_multi_scale_molecular_dynamics/models/mlip/ace.py
src/diffusion_for_multi_scale_molecular_dynamics/models/mlip/mtp.py
src/diffusion_for_multi_scale_molecular_dynamics/models/mlip/utils.py
src/diffusion_for_multi_scale_molecular_dynamics/oracle/energy_oracle.py
src/diffusion_for_multi_scale_molecular_dynamics/oracle/lammps_energy_oracle.py
src/diffusion_for_multi_scale_molecular_dynamics/utils/maxvol.py
tests/active_learning_loop/test_benchmark.py
tests/models/mlip/test_ace.py
tests/models/mlip/test_mtp.py
tests/models/test_axl_diffusion_lightning_model.py
tests/oracle/test_lammps_energy_oracle.py
tests/utils/test_maxvol.py

In this PR, I added the functionalities to handle multiple atom types with MTP and ACE.
There could be issues with maxvol with multiple atom types, this should be investigated asap.
I also made the code review modifications requested and updated a unit test.
ACE will not support unlabeled examples, this is another TODO asap.

Al multiple atom types

---

data/process_lammps_data.py
examples/config_files/diffusion/config_diffusion_egnn.yaml
examples/config_files/diffusion/config_diffusion_mlp.yaml
examples/config_files/diffusion/config_diffusion_mlp_orion.yaml
src/diffusion_for_multi_scale_molecular_dynamics/callbacks/sampling_visualization_callback.py
src/diffusion_for_multi_scale_molecular_dynamics/generators/axl_generator.py
src/diffusion_for_multi_scale_molecular_dynamics/oracle/energy_oracle.py
src/diffusion_for_multi_scale_molecular_dynamics/oracle/lammps_energy_oracle.py

Small fixes so the code works with or without fixed parameters. This covers MLP and EGNN, but not MACE (and variations).

Repairing march2025

---

src/diffusion_for_multi_scale_molecular_dynamics/generators/instantiate_generator.py
src/diffusion_for_multi_scale_molecular_dynamics/oracle/energy_oracle.py
src/diffusion_for_multi_scale_molecular_dynamics/sample_diffusion.py
tests/test_sample_diffusion.py
tutorials/repaint_02.ipynb
tutorials/simple_experiment_01.ipynb

I adapt the sampling script so that it can take in a `sampling_constraint` object. 
I also clean some knick-knack here and there.

Fix sampling

---

resources/flare/Containerfile_FLARE_and_ARTn

A new container file for a podman with FLARE + LAMMPS + ARTn.

A new container file for FLARE+LAMMPS+ARTn

---

src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/dynamic_driver/artn.template

I think this is the lammps command they were talking about.

Add the lammps no-sort command.

---

src/diffusion_for_multi_scale_molecular_dynamics/oracle/lammps_energy_oracle.py

I'm training a new Si 3x3x3 model to try Normand's idea (my old models have all been deleted from the Scratch folder on the cluster).
My training job crashed because some force entry wasn't a float. I guess the forces were the string 'nan', and could not be turned into an array of numbers, which crashed my training job.
Hopefully this fixes the issue.

Fix crashing forces.
