- README.md
- hooks/pre-commit_staged
- setup.py
Here's a better pre-commit script that I created for another project. With this script, git won't complain for
files that are not staged, so we don't get a deluge of complaints every time we want to commit anything. 
This is useful in a development context where there may be a bunch of ad hoc, non committed files floating around.
The original pre-commit script is still what is being run in CI.
> New pre-commit script

- crystal_diffusion/__init__.py
- crystal_diffusion/analysis/__init__.py
- crystal_diffusion/analysis/plot_style.txt
- crystal_diffusion/analysis/target_score_analysis.py
- crystal_diffusion/score/wrapped_gaussian_score.py
- requirements.txt
- tests/score/test_wrapped_gaussian_score.py
This code implements the target score network, as described in the Section II.C of the overleaf document. 
The idea is to split the definition into subparts such that all terms converge quickly. 
There is also a plotting script that shows evidence that the score is correct and converges very quickly.
> Score target

- crystal_diffusion/data/diffusion/data_loader.py
- crystal_diffusion/data/diffusion/data_preprocess.py
- crystal_diffusion/models/model_loader.py
- crystal_diffusion/train_diffusion.py
- examples/local/config_diffusion.yaml
- examples/local/run_diffusion.sh
- tests/data/diffusion/test_data_loader.py
- tests/data/diffusion/test_data_preprocess.py
Changing the train.py entry point to handle a diffusion model instead in train_diffusion.py.
This trains the model end-to-end on real data! 
examples/local/run_diffusion.sh gives an example on how to do this
Reorganization of the config file to handle the different arguments as cleanly as possible. We should check the library simple_parsing in the future to clean up even more.
Rewrite the load_model function - some cleaning will be required in the future if we integrate simple_parsing.
Harmonize the names of variables between the dataloader and the model. 
Training a model requires about 45 minutes of preprocessing at the moment. This is only done once - to create .parquet file that are parsed by the library Datasets. 
TODO: integrate orion and more metrics in tensorboard
> Diffusion training

- crystal_diffusion/models/score_network.py
- crystal_diffusion/samplers/noisy_position_sampler.py
- crystal_diffusion/score/wrapped_gaussian_score.py
> fixing broken device swap

- crystal_diffusion/callbacks/callback_loader.py
- crystal_diffusion/callbacks/callbacks.py
- crystal_diffusion/callbacks/sampling_callback.py
- crystal_diffusion/loggers/logger_loader.py
- crystal_diffusion/models/position_diffusion_lightning_model.py
- examples/local/diffusion/config_diffusion.yaml
- sanity_checks/overfit_fake_data.py
- tests/test_train_diffusion.py
A first crack at periodically sampling the model while training, through a callback.
I also refactor how the loss is logged, to make it super extra explicit what is logged at every step and what is aggregated at every epoch.
There's a lot of possible improvement as future work:
- there's not a lot of repetition in the input parameters... It would be nice to not have to repeat ourselves
- the histogram image that is logged is pretty bare boned: it would be nice to overlay over the validation data, but that's complicated to do right now.
> Sampling callback

- crystal_diffusion/callbacks/sampling_callback.py
- crystal_diffusion/models/mace_utils.py
- crystal_diffusion/models/position_diffusion_lightning_model.py
- crystal_diffusion/models/score_network.py
- crystal_diffusion/samplers/predictor_corrector_position_sampler.py
- requirements.txt
- tests/models/test_mace_utils.py
- tests/models/test_position_diffusion_lightning_model.py
- tests/models/test_score_network.py
- tests/samplers/test_predictor_corrector_position_sampler.py
This new function takes the score network input and creates a graph usable by MACE. 
I added the mace library and pytorch-geometric as requirements.
I used a placeholder for the adjacency matrix - this is developed in another branch.
I had to add the unit_cell as a passed arguments to the score network input - along fixing the related unit tests.
This method is fully GPU friendly. It might be a bit slow, but this is beyond the scope of this project to accelerate pytorch-geometric :)
> Convert score network input to mace graph input

- crystal_diffusion/models/mace_utils.py
- crystal_diffusion/utils/neighbors.py
- tests/models/test_mace_utils.py
- tests/utils/test_neighbors.py
This PR fixes an issue in the 'batch tensor' output of the adjacency matrix calculation code. It also tests that the graphs generated by MACE and our approach are identical, up to a permutation of edge indices.
I also remove a bunch of code around ` convert_adjacency_info_into_batched_and_padded_data`. This functionality is not needed and was only introduced because the required output format wasn't clear to me at the time. There is no need to carry this dead wood around, so I tested the code that generates the adjacency matrix and remove this useless stuff.
> Testing adjacency matrix

- crystal_diffusion/analysis/analytic_score/perfect_score_loss_analysis.py
- crystal_diffusion/analysis/analytic_score/sample_quality_with_energy_analysis.py
- crystal_diffusion/analysis/analytic_score/sample_visualization_analysis.py
- crystal_diffusion/analysis/analytic_score/score_convergence_analysis.py
- crystal_diffusion/analysis/analytic_score/utils.py
- crystal_diffusion/analysis/diffusion_sample_position_analysis.py
- crystal_diffusion/analysis/positions_to_cif_files.py
- crystal_diffusion/callbacks/analysis_callbacks.py
- crystal_diffusion/callbacks/loss_monitoring_callback.py
- crystal_diffusion/callbacks/sampling_callback.py
- crystal_diffusion/models/analytical_score_network.py
- crystal_diffusion/models/diffusion_mace.py
- crystal_diffusion/models/position_diffusion_lightning_model.py
- crystal_diffusion/models/score_network.py
- experiments/diffusion_mace_harmonic_data/diffusion_mace_score_loss_analysis.py
- requirements.txt
- sanity_checks/overfit_fake_data.py
- sanity_checks/sanity_check_callbacks.py
- tests/models/test_analytical_score_network.py
- tests/models/test_diffusion_mace.py
- tests/models/test_score_network.py
- tests/test_train_diffusion.py
Code to generate some 'fake' harmonic data, as well as some ad hoc mini-experiments to investigate the behavior of various models in the 2 atoms in 3D setting.
Various results and interpretations related to this code are presented in https://www.notion.so/Can-we-compute-an-analytic-approximation-to-the-score-network-ab3780fc19de4af38589e66c2324f182.
The high level conclusions are:
- "Diffusion MACE", as currently implemented, doesn't seem to learn anything
- "Vanilla MACE + Equivariant Head" does pretty well, even if the loss doesn't go as low as the theoretical minimum... The samples seem to look pretty good still!
This suggest that we should modify 'Diffusion MACE' to better match the Equivariant Head that was tacked on top of Vanilla MACE... This is work for another day.
> Analytic score

- crystal_diffusion/models/score_prediction_head.py
original model:
time embedding + mace output -> 
o3.Linear -> o3.BatchNorm -> o3.TensorSquare -> non linearity
The TensorSquare had a lot of weights and was probably overkill for our purpose. Its goal was to mix the time information across the different channels of MACE, but it was also computing a lot of useless stuff. 
I replaced with the following:
FullyConnectedTensorProduct(time embedding, mace output) ->
o3.Linear -> o3.BatchNorm -> non linearity
the FCTP mixes time with all the components of the mace output and we can control the dimensionality of its output. No need for a TensorSquare anymore
We probably could simplify even more by allowing only the 0e channel as the output of the FCTP since the next layers should not mix different ells
> rewrite the mace equivariant head to avoid a model explosion

- crystal_diffusion/train_diffusion.py
- examples/local/diffusion/config_diffusion_mace.yaml
- examples/local/diffusion/config_diffusion_mlp.yaml
- examples/local/diffusion/config_mace_equivariant_head.yaml
- examples/local/diffusion/config_mace_mlp_head.yaml
Adding a kwarg to allow for gradient accumulation.
In the normal MACE and the MLP score network, there is no batchnorm, so doing gradient accumulation is easy.
Here, just passing an argument to pytorch-lightning trainer does the trick.
TBD what happens with DiffusionMACE with the o3.batchnorm...
> gradient accumulation

- crystal_diffusion/models/diffusion_mace.py
- crystal_diffusion/models/scheduler.py
- crystal_diffusion/utils/sample_trajectory.py
- examples/mila_cluster/diffusion/config_diffusion_mace.yaml
- experiments/si_diffusion_1x1x1/config_diffusion_mace.yaml
> Difface fixes

- crystal_diffusion/callbacks/sampling_callback.py
- crystal_diffusion/generators/sde_position_generator.py
- crystal_diffusion/models/score_fokker_planck_error.py
- crystal_diffusion/samplers/exploding_variance.py
- crystal_diffusion/utils/sample_trajectory.py
- requirements.txt
- sanity_checks/generators/__init__.py
- sanity_checks/generators/sde_generator_sanity_check.py
- tests/generators/conftest.py
- tests/generators/test_constrained_langevin_generator.py
- tests/generators/test_langevin_generator.py
- tests/generators/test_ode_position_generator.py
- tests/generators/test_predictor_corrector_position_generator.py
- tests/generators/test_sde_position_generator.py
- tests/models/test_score_fokker_planck_error.py
- tests/samplers/test_exploding_variance.py
Implementation of a Score Fokker-Planck Error calculator, as defined in the paper
"FP-Diffusion: Improving Score-based Diffusion Models by Enforcing  the Underlying Score Fokker-Planck Equation".
The code makes extensive use of Pytorch autograd; the main entry point is `ScoreFokkerPlanckError. get_score_fokker_planck_error`.
> Fokker planck

- .github/workflows/ci.yml
- README.md
- pyproject.toml
- tests/score/test_wrapped_gaussian_score.py
- uv.lock
A few low hanging fruits to accelerate the execution of pytest.
> Pytest speedup

- experiments/atom_types_only_experiments/patches/identity_relative_coordinates_langevin_generator.py
- src/diffusion_for_multi_scale_molecular_dynamics/analysis/sample_trajectory_analyser.py
- src/diffusion_for_multi_scale_molecular_dynamics/generators/axl_generator.py
- src/diffusion_for_multi_scale_molecular_dynamics/generators/langevin_generator.py
- src/diffusion_for_multi_scale_molecular_dynamics/generators/predictor_corrector_axl_generator.py
- src/diffusion_for_multi_scale_molecular_dynamics/utils/d3pm_utils.py
- src/diffusion_for_multi_scale_molecular_dynamics/utils/sample_trajectory.py
- tests/generators/conftest.py
- tests/generators/test_langevin_generator.py
- tests/generators/test_predictor_corrector_position_generator.py
- tests/loss/test_atom_type_loss_calculator.py
- tests/utils/test_d3pm_utils.py
The bulk of this PR is about modifying the Langevin generator to (1) avoid accidental transmutation and (2) insure all atoms are unmasked at the last time step.  One key aspect of achieving this is to no longer clip the denominator in `get_probability_at_previous_time_step`, but to clip  each class probability instead.
> Test greedy sampling

- experiments/dataset_analysis/dataset_covariance.py
- experiments/regularization_toy_problem/visualize_score_vector_field_2D.py
- src/diffusion_for_multi_scale_molecular_dynamics/analysis/score_viewer.py
- src/diffusion_for_multi_scale_molecular_dynamics/callbacks/score_viewer_callback.py
- src/diffusion_for_multi_scale_molecular_dynamics/models/egnn.py
- src/diffusion_for_multi_scale_molecular_dynamics/models/score_networks/mlp_score_network.py
- src/diffusion_for_multi_scale_molecular_dynamics/noise_schedulers/exploding_variance.py
- src/diffusion_for_multi_scale_molecular_dynamics/noise_schedulers/noise_parameters.py
- src/diffusion_for_multi_scale_molecular_dynamics/noise_schedulers/sigma_calculator.py
- src/diffusion_for_multi_scale_molecular_dynamics/regularizers/fokker_planck_regularizer.py
- src/diffusion_for_multi_scale_molecular_dynamics/sample_diffusion.py
- tests/models/score_network/test_score_network_equivariance.py
- tests/models/score_network/test_score_network_general_tests.py
- tests/models/test_egcl.py
- tests/noise_schedulers/test_exploding_variance.py
- tests/noise_schedulers/test_sigma_calculator.py
- tests/regularizers/conftest.py
- tests/regularizers/differentiable_score_network.py
In this PR, I
- modify the behavior of EGNN when `normalize=True` to try to avoid discontinuous jumps in the score.
- I add an optional time dependent prefactor in the MLP architecture
- I create a configurable `sigma(t)` schedule. The options are now `exponential` (what we have used so far) and `linear`.
> Architecture inductive bias

- src/diffusion_for_multi_scale_molecular_dynamics/models/score_networks/egnn_score_network.py
- src/diffusion_for_multi_scale_molecular_dynamics/utils/lattice_utils.py
- src/diffusion_for_multi_scale_molecular_dynamics/utils/neighbors.py
- src/diffusion_for_multi_scale_molecular_dynamics/utils/structure_utils.py
- tests/models/score_network/test_score_network_equivariance.py
- tests/models/score_network/test_score_network_general_tests.py
- tests/utils/test_lattice_utils.py
- tests/utils/test_neighbors.py
Here I add the possibility of using more reciprocal lattice vectors (K vectors) in complete shells in the EGNN architecture. 
Referring to our Latex document, the embedding to high-dimensional  Euclidean space takes the form
Since we have inversion symmetry, and we don't want to manipulate complex numbers, this becomes
and the model takes the form
To preserve point group symmetry, the K vectors must be present in complete symmetry shells. 
The previous code was equivalent to limiting ourselves to `number_of_shells = 1`. This new code allows use to use more shells. 
This is probably not a huge improvement, but it was silly to limit ourselves to the first shell: comparable papers use "positional embedding" with many more Fourier modes.
> More k shells

- .github/workflows/ci.yml
- README.md
- pyproject.toml
- tests/models/mlip/test_ace.py
- uv.lock
I try to clean up the install workflow. By making `pyace` an optional dependency, it is left to the user to decide whether to install it or not (the tests will adapt to whether the library is there or not). Also, `uv` will take care of installing these dependencies from github, so we don't have to clone these repos locally and manage that mess.
> Clean pyace install

- analysis_and_sanity_checks/atom_types_only_experiments/patches/fixed_position_data_module.py
- pyproject.toml
- src/diffusion_for_multi_scale_molecular_dynamics/callbacks/callback_loader.py
- src/diffusion_for_multi_scale_molecular_dynamics/callbacks/loss_monitoring_callback.py
- src/diffusion_for_multi_scale_molecular_dynamics/callbacks/sampling_visualization_callback.py
- src/diffusion_for_multi_scale_molecular_dynamics/callbacks/score_viewer_callback.py
- src/diffusion_for_multi_scale_molecular_dynamics/callbacks/standard_callbacks.py
- src/diffusion_for_multi_scale_molecular_dynamics/data/diffusion/gaussian_data_module.py
- src/diffusion_for_multi_scale_molecular_dynamics/data/diffusion/instantiate_data_module.py
- src/diffusion_for_multi_scale_molecular_dynamics/data/diffusion/lammps_for_diffusion_data_module.py
- src/diffusion_for_multi_scale_molecular_dynamics/loggers/logger_loader.py
- src/diffusion_for_multi_scale_molecular_dynamics/models/axl_diffusion_lightning_model.py
- src/diffusion_for_multi_scale_molecular_dynamics/train_diffusion.py
- tests/models/test_axl_diffusion_lightning_model.py
- uv.lock
I was playing with matgl, and there was a naming clash. 
The preferred way of naming "pytorch lightning" is just "lightning". They are dragging a nice name confusion since 2022
(see https://github.com/Lightning-AI/pytorch-lightning/discussions/16688). Both `pytorch-lightning` and `lightning` are used, but the latter is preferred. 
I observed a subtle collision between matgl and our old fashioned naming scheme (long boring story). 
I propose to just get on board with the new naming convention. I also increment the library version to the latest (2.5.1). This should have no effect on our code.
> Increment Pytorch-Lightning

- src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/active_learning.py
- src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/sample_maker/base_sample_maker.py
- src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/sample_maker/excise_and_repaint_sample_maker.py
- src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/single_point_calculators/base_single_point_calculator.py
- tests/active_learning_loop/sample_maker/test_base_sample_maker.py
- tests/active_learning_loop/sample_maker/test_excise_and_repaint_sample_maker.py
In this PR, I added dictionaries of additional informations from samples. This exposes the central atom index when using an Excision sample maker. This should make the ExciseAndRepaintSampleMaker compatible with the current AL code (fingers crossed, I am limited in my current testing from a non-working env - I'll try working in a podman to test stuff).
> adding information dicts with sample makers

- experiments/active_learning_si_sw/launch_active_learning.py
- experiments/active_learning_si_sw/plot_barrier.py
- src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/active_learning.py
- src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/logging.py
- src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/sample_maker/base_sample_maker.py
- src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/trainer/flare_hyperparameter_optimizer.py
- src/diffusion_for_multi_scale_molecular_dynamics/active_learning_loop/trainer/flare_trainer.py
- tests/active_learning_loop/trainer/test_flare_hyperparameter_optimizer.py
In this PR:
- I fix the problem in the "sample_maker" configuration class. It turns out you have to TYPE everything the same way in a child class or else you get problems.
- I fix the overlogging problem, where loggers would step on each other's toes
- I revamp how the hyperparameters of a FLARE model are optimized, including not optimizing them at all. 
- I change some knick-knack here and there.
> Optimize flare better
